// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.commands.groups;

import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;

//import frc.robot.commands.*;
import frc.robot.commands.hinge.*;
//import frc.robot.commands.grasper.*;
//import frc.robot.commands.feeder.*;
//import frc.robot.commands.shooter.*;
//import frc.robot.commands.arms.*;
//import frc.robot.commands.elbows.*;


/**
 *
 */
public class AlmostEverythingStop extends SequentialCommandGroup {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
	public AlmostEverythingStop() {
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
		// Add Commands here:
		// e.g. addSequential(new Command1());
		//      addSequential(new Command2());
		// these will run in order.

		// To run multiple commands at the same time,
		// use addParallel()
		// e.g. addParallel(new Command1());
		//      addSequential(new Command2());
		// Command1 and Command2 will run in parallel.

		// A command group will require all of the subsystems that each member
		// would require.
		// e.g. if Command1 requires chassis, and Command2 requires arm,
		// a CommandGroup containing them would require both the chassis and the
		// arm.
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
		//addSequential(new HingeStop());

		addCommands(
			new HingeStop());

		//addSequential(new GrasperStop());
		//addSequential(new FeederStop());
		//addSequential(new ShooterStop());

		//addSequential(new FrontElbowsStop());
		//addSequential(new RearElbowsStop());
		//addSequential(new FrontArmsStop());
		//addSequential(new RearArmsStop());
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 
	} 
}
